// Auto-generated by tools/espkm.py from keymaps YAML; DO NOT EDIT
#pragma once

#include "espkm/keycodes.h"

#define ESPKM_GENERATED_LAYERS 1
static const keycode_t generated_layer_0[] = {
    KC_BASIC(KC_Q), KC_BASIC(KC_W), KC_BASIC(KC_E),
    KC_BASIC(KC_A), KC_BASIC(KC_S), KC_BASIC(KC_D),
};

static const keycode_t *generated_layers[] = {
    generated_layer_0,
};
