name: ESP-KF Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/esp/esp-idf
            ~/.espressif
          key: esp-idf-s3-${{ runner.os }}

      - run: |
          sudo apt update
          sudo apt install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util

      - run: |
          if [ ! -d ~/esp/esp-idf ]; then
            mkdir -p ~/esp
            cd ~/esp
            git clone --recursive https://github.com/espressif/esp-idf.git
            cd esp-idf
            ./install.sh esp32s3
          fi

      - run: |
          source ~/esp/esp-idf/export.sh
          idf.py set-target esp32s3
          idf.py build
